# This script creates a list of default columns that the fetch_asycuda...
# functions use for the default columns, in the event that no columns are listed.

# Maintained by: Mohamed Ali Bah (MRP), Jordan Imahori (ODI Fellow)
# Contact: mahbah@nra.gov.sl; jordan.imahori@gmail.com


# To update the default columns, add/remove column names here, ensuring that
# the names match exactly those in the data warehouse.


IE_INCLUDE = c('OFFICECODE', 'REGNBER', 'REGDATE', 'DECTYPE', 'DECREF',
               'ASMTNBR', 'RCPTNBR', 'RCPTDATE', 'MANIFESTNBR', 'CONSIGNEETIN',
               'CONSIGNEENAME', 'AGENTTIN', 'AGENTNAME', 'CHANNEL', 'MODEOFPAYMENT',
               'ITEM', 'COMMODITYCODE',  'PRODUCTDESC', 'COMMERCIALDESC', 'CPCEXT',
               'CPCNAT', 'CPCNATDESC', 'ORIGINCITY', 'ORIGINCITYNAME',
               'DESTINATIONCITYCODE', 'DESTINATIONCITYNAME', 'PKGNBR',
               'NETWGT', 'GROSSWGT', 'PKGCODE', 'PKGNAME', 'SUPQTY', 'SUPUOM',
               'CIFVALUE', 'INVOICEFCXAMOUNT', 'INVOICECURCODE', 'INVOICECURRATE',
               'EXT_FREIGHTAMT', 'EXT_FREIGHTCURCODE', 'EXT_FREIGHTCURRATE',
               'INT_FREIGHTAMT', 'INT_FREIGHTCURCODE', 'INT_FREIGHTCURRATE',
               'INSURANCEAMT', 'INSURANCECURCODE',  'INSURANCECURAMT', 'OTHERCOSTSAMT',
               'OTHERCOSTSCURCODE', 'OTHERCOSTSCURRATE', 'DEDUCTIONSAMT',
               'DEDUCTIONSCURCODE', 'DEDUCTIONSCURRATE', 'IMPORTDUTY', 'IMPORTDUTY_RATE',
               'ECOWASLEVY', 'ECOWASLEVY_RATE', 'GST', 'GST_RATE', 'WITHHOLDINGTAX',
               'WITHHOLDINGTAX_RATE', 'PROCESSINGFEES', 'PETROLEUMEXCISE',
               'PETROLEUMEXCISE_RATE', 'DOMESTICEXICEDUTY', 'DOMESTICEXICEDUTY_RATE',
               'ROADUSERCHARGE', 'ROADUSERCHARGE_RATE', 'IMPORTEXCISE',
               'IMPORTEXCISE_RATE', 'INFRA_DEVT_FUND', 'INFRA_DEVT_FUND_RATE',
               'ASMTDATE', 'PAYDATE', 'RELEASEDATE', 'CLEARDATE', 'EXITDATE',
               'REROUTETOREDDATE', 'REROUTETOYELLOWDATE', 'REROUTETOBLUEDATE',
               'REROUTETOGREENDATE', 'SELECTIVTITYDATE', 'QUERYDATE',
               'REALLOCATEDATE', 'CURRENT_STATUS')

PCA_INCLUDE = c('OFFICECODE', 'REGNBER', 'REGDATE', 'DECTYPE', 'DECREF', 'ASMTNBR',
                'ASMTDATE', 'RCPTNBR', 'RCPTDATE', 'MANIFESTNBR', 'CONSIGNEECODE',
                'CONSIGNEENAME', 'AGENTTIN', 'AGENTNAME', 'EXPORTERCODE',
                'EXPORTERNAME', 'CHANNEL', 'SECTION', 'ITEM', 'COMMODITYCODE',
                'PRODUCTDESC', 'COMMERCIALDESC', 'EXTENDEDCPC', 'NATIONALCPCCODE',
                'NATIONALCPCDESC', 'PREFCODE', 'PREVIOUSDOC', 'PKGCODE', 'PKGNAME',
                'ORIGINCITY', 'PKGNBR', 'NETWGT', 'GROSSWGT', 'SUPQTY', 'SUPUOM',
                'INVOICEAMT', 'INVOICECURCODE', 'INVOICECURRATE', 'INTERNALFREIGHTAMT',
                'INTERNALFREIGHTCURCODE', 'INTERNALFREIGHTCURRATE', 'EXTERNALFREIGHTAMT',
                'EXTERNALFREIGHTCURCODE', 'EXTERNALFREIGHTCURRATE', 'INSURANCEAMT',
                'INSURANCECURCODE', 'INCURANCECURRATE', 'CIFVALUE', 'IMPORTDUTY',
                'IMPORTDUTY_RATE', 'ECOWASLEVY', 'ECOWASLEVY_RATE', 'GST', 'GST_RATE',
                'WITHHOLDINGTAX', 'WITHHOLDINGTAX_RATE', 'PROCESSINGFEES',
                'PETROLEUMEXCISE', 'PETROLEUMEXCISE_RATE', 'DOMESTICEXICEDUTY',
                'DOMESTICEXICEDUTY_RATE', 'ROADUSERCHARGE', 'ROADUSERCHARGE_RATE',
                'IMPORTEXCISE', 'IMPORTEXCISE_RATE', 'INFRA_DEVT_FUND',
                'INFRA_DEVT_FUND_RATE')

RMU_INCLUDE = c('OFFICECODE', 'REGNUMBER1', 'REGDATE', 'DECTYPE', 'DECREF', 'CONSIGNEETIN',
                'DECLARANTTIN', 'DECLARANTNAME', 'CONSIGNEENAME', 'CONTAINERIZED',
                'CONTAINERTOTAL', 'TOTALTAXES', 'ADDITIONALTAXES', 'ENTRYSTATUS',
                'COMMODITYCODE', 'COMMODITYDESC', 'COUNTRYOFORIGIN','CIF', 'STATISTICALVALUE',
                'ITEMTAXAMOUNT', 'IMPORTDUTY', 'ECOWASLEVY', 'GST', 'WITHHOLDINGTAX', 'PROCESSINGFEES',
                'PETROLEUMEXCISE', 'DOMESTICEXICEDUTY', 'ROADUSERCHARGE', 'IMPORTEXCISE')


QA_INCLUDE = c('DOCUMENTID', 'OFFICECODE', 'REGDATE', 'REGNUMBER', 'DECREF',
               'DECREFYEAR', 'ITEMS', 'DECLARANTTIN', 'DECLARANTNAME', 'CONSIGNEETIN',
               'CONSIGNEENAME', 'TOTALTAXES', 'ADDITIONALTAXES', 'SECTION',
               'CONTAINERIZED', 'CONTAINERTOTAL', 'CHANNEL', 'ENTRYSTATUS',
               'AMMENDMENTDATE', 'INSPECTIONINFO', 'FRAUDCODE1', 'FRAUDNAME1',
               'FRAUDCODE2', 'FRAUDNAME2', 'FRAUDCODE3', 'FRAUDNAME3', 'FRAUDCODE4',
               'FRAUDNAME4', 'FRAUDCODE5', 'FRAUDNAME5', 'FRAUDCODE6', 'FRAUDNAME6',
               'CONFORM', 'REVENUELOSS', 'PENALTYAMOUNT')


# Save these as internal data
usethis::use_data(IE_INCLUDE, PCA_INCLUDE, RMU_INCLUDE, QA_INCLUDE,
                  internal = TRUE, overwrite = TRUE)
